/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigInt,
  BigIntish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface UniswapV2FlashSwapInterface extends utils.Interface {
  functions: {
    "amountToRepay()": FunctionFragment;
    "flashSwap(uint256)": FunctionFragment;
    "uniswapV2Call(address,uint256,uint256,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "amountToRepay" | "flashSwap" | "uniswapV2Call"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "amountToRepay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "flashSwap",
    values: [PromiseOrValue<BigIntish>]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapV2Call",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigIntish>,
      PromiseOrValue<BigIntish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "amountToRepay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "flashSwap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV2Call",
    data: BytesLike
  ): Result;

  events: {};
}

export interface UniswapV2FlashSwap extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UniswapV2FlashSwapInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    amountToRepay(overrides?: CallOverrides): Promise<[BigInt]>;

    flashSwap(
      wethAmount: PromiseOrValue<BigIntish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    uniswapV2Call(
      sender: PromiseOrValue<string>,
      amount0: PromiseOrValue<BigIntish>,
      amount1: PromiseOrValue<BigIntish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  amountToRepay(overrides?: CallOverrides): Promise<BigInt>;

  flashSwap(
    wethAmount: PromiseOrValue<BigIntish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  uniswapV2Call(
    sender: PromiseOrValue<string>,
    amount0: PromiseOrValue<BigIntish>,
    amount1: PromiseOrValue<BigIntish>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    amountToRepay(overrides?: CallOverrides): Promise<BigInt>;

    flashSwap(
      wethAmount: PromiseOrValue<BigIntish>,
      overrides?: CallOverrides
    ): Promise<void>;

    uniswapV2Call(
      sender: PromiseOrValue<string>,
      amount0: PromiseOrValue<BigIntish>,
      amount1: PromiseOrValue<BigIntish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    amountToRepay(overrides?: CallOverrides): Promise<BigInt>;

    flashSwap(
      wethAmount: PromiseOrValue<BigIntish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigInt>;

    uniswapV2Call(
      sender: PromiseOrValue<string>,
      amount0: PromiseOrValue<BigIntish>,
      amount1: PromiseOrValue<BigIntish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigInt>;
  };

  populateTransaction: {
    amountToRepay(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    flashSwap(
      wethAmount: PromiseOrValue<BigIntish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    uniswapV2Call(
      sender: PromiseOrValue<string>,
      amount0: PromiseOrValue<BigIntish>,
      amount1: PromiseOrValue<BigIntish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
